### ISSUE TITLE
docker distribution: bundle, compose, optional dependencies?

### ISSUE THREAD

**Issue by vanatteveldt** [vanatteveldt/nlpipe#12]
I made an experimental docker distribution and I think that is a great way to get non-linux people to use nlpipe.

This raises the question whether and how we want to distribute systems with NLP tools included. The docker I made includes CoreNLP, but of course that makes it pretty big, and other people made dockers specifically for CoreNLP. I think we should probably distribute a docker with only our server+workers, and either offer something like a compose script for nlpipe+corenlp, or simply tell the user to also install the corenlp docker if they want to use that; and then have the corenlp worker check for port 9000 and error if no corenlp server can be found. @koheiw, what do you think?

(of course, power users will probably still want to install normally, and that is fine, this is aimed mostly at casual users I think)

**Comment by vanatteveldt** [comment]
I've had a go with docker-compose, it seems to work really neatly. The nlpipe docker is now just the nlpipe server and workers, and assumes that corenlp is listening at port 9000. Then, you can define a compose script like this:

```
nlpipe:
  image: vanatteveldt/nlpipe
  ports:
  - "5001:5001"
  links:
  - corenlp
  environment:
  - CORENLP_HOST=http://corenlp:9000
corenlp:
  image: chilland/corenlp-docker
```

Then, you just run `docker-compose up`, which will download and run both nlpipe and corenlp, and you can use nlpipe at port 5001.

We can publish a number of 'useful' nlpipe compositions, e.g. serevr+corenlp, server+corenlp+dutch, etc, and people can just run then in a single command.

@koheiw @kasperwelbers agree that this is the way to go?
